[project]
name = "generators-in-testing"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "pytest>=8.4.0",
    "pytest-playwright>=0.7.0",
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
]
